FILES = $(addsuffix .cht,  $(basename $(wildcard iso/songs/*.json))) \
		$(addsuffix .cht,  $(basename $(wildcard iso/songs/*/*.json)))

all: \
	$(FILES) \

iso/%.cht: iso/%.json
	tools/funkinchtpak/funkinchtpak $< $@

.PHONY: clean
clean:
	rm -f $(FILES)
