all: \
  $(addsuffix .cht,  $(basename $(wildcard iso/songs/*.json))) \
  $(addsuffix .cht,  $(basename $(wildcard iso/songs/*/*.json))) \

iso/%.cht: iso/%.json
	tools/funkinchtpak/funkinchtpak $< $@
