name: ISO

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Psy-Q build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libtinyxml2-dev gcc-mipsel-linux-gnu g++-mipsel-linux-gnu binutils-mipsel-linux-gnu
        version: 1.0

    - name: Restore FFmpeg
      id: cache-ffmpeg
      uses: actions/cache/restore@v3
      with:
        path: ffmpeg
        key: ffmpeg-6.0

    - name: Install and Build FFmpeg
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
      run: |
        wget http://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
        tar Jxf ffmpeg-6.0.tar.xz

        cd ffmpeg-6.0
        sudo ./configure --prefix=../ffmpeg --enable-shared --disable-static --enable-small --disable-programs --disable-doc --disable-avdevice --disable-postproc --disable-avfilter --disable-network --disable-encoders --disable-hwaccels --disable-muxers --disable-bsfs --disable-devices --disable-filters --disable-mmx
        make -j
        sudo make install

    - name: Cache FFmpeg
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
      id: save-ffmpeg
      uses: actions/cache/save@v3
      with:
        path: ffmpeg
        key: ffmpeg-6.0

    - name: Move FFmpeg path
      run: |
        sudo mv ffmpeg/lib/* /usr/local/lib
        sudo mv ffmpeg/include/* /usr/local/include

        sudo ldconfig

    - name: Install mkpsxiso
      run: |
        wget https://github.com/Lameguy64/mkpsxiso/releases/download/v2.03/mkpsxiso-2.03-Linux.deb
        sudo dpkg -i mkpsxiso-2.03-Linux.deb

    - name: Restore PsyQ
      id: cache-psyq
      uses: actions/cache/restore@v3
      with:
        path: mips/psyq
        key: psyq

    - name: Download PsyQ
      if: steps.cache-psyq.outputs.cache-hit != 'true'
      run: |
        cd mips
        wget http://psx.arthus.net/sdk/Psy-Q/psyq-4_7-converted-light.zip
        unzip psyq-4_7-converted-light.zip
        mv psyq-4_7-converted psyq
        wget https://archive.org/download/psyq-sdk/PSYQ_SDK.zip/psyq%2Fcdgen%2FLCNSFILE%2FLICENSEA.DAT -O psyq/LICENSEA.DAT
        
    - name: Cache PsyQ
      if: steps.cache-psyq.outputs.cache-hit != 'true'
      id: save-psyq
      uses: actions/cache/save@v3
      with:
        path: mips/psyq
        key: psyq
        
    - name: Compile tools
      run: |
        make -f Makefile.tools
        mv ./mips/psyq/LICENSEA.DAT licensea.dat
              
    - name: Compile PSXFunkin
      run: |
        sed -i 's/\/\/#define RELEASE_MODE/#define RELEASE_MODE/' src/psx/configuration.h
        make -f Makefile.assets
        make
        mkpsxiso -y funkin.xml
      
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: PSXFunkin Potage Engine
        path: |
          funkin.bin
          funkin.cue